### ISSUE TITLE
Configure module path aliases for imports

### ISSUE THREAD

**Issue by Nabeel77** [tmrev/tmrev.io#19]
In order to import a module, absolute path has to be defined. It can be confusing in a sense that if there are two modules with same names in two different directories, a new comer might make a mistake and import from wrong module and it is also time consuming.

For example: '../../../../components/common/typography/headerText'. This import can be shortened to '@/components/common/typography/headerText' by using module path alias. That way we do not need to worry about the absolute path as path aliases will automatically import from correct dir/module. 

I would love to implement it if you agree.

**Comment by KegenGuyll** [comment]
This is a great suggestion!

**Comment by Nabeel77** [comment]
> This is a great suggestion!

If you agree, should I go ahead and implement it?

**Comment by Nabeel77** [comment]
On it. Thank you :)

**Comment by KegenGuyll** [comment]
closed by PR; merged into Dev
