### ISSUE TITLE
WEEKEND BOX OFFICE PERFORMANCE chart is tough to see grid lines.

### ISSUE THREAD

**Issue by kiyanpourmaleki** [tmrev/tmrev.io#25]
Can I take this issue and change the color of the grid lines to fit the theme and be more visible? Would like to contribute.

**Comment by KegenGuyll** [comment]
This is a great first issue!

**Comment by KegenGuyll** [comment]
> what is required in .env.local to run locally

https://github.com/tmrev/tmrev.io/wiki/Getting-Started-with-tmrev-io-(creationals) @kiyanpourmaleki

**Comment by kiyanpourmaleki** [comment]
what is meant by client email and project id for .env.local from json file
