### ISSUE TITLE
Suggest to move search from burger-menu to navbar

### ISSUE THREAD

**Issue by ayronman99** [tmrev/tmrev.io#27]
![image](https://user-images.githubusercontent.com/65846152/232179084-5cdb691c-f892-48cc-80cc-56033df6714a.png)

**Comment by KegenGuyll** [comment]
What is your thought process behind this request?

**Comment by ayronman99** [comment]
It's a UX type, so users dont need two steps to access search. We want to users to able to search with less step.

**Comment by caycekoehler** [comment]
Unless we divide search into various types. If it is understood at it's base though as a movie first search then I fully agree.
