### ISSUE TITLE
Suggest to change background color of body

### ISSUE THREAD

**Issue by john-seredich** [tmrev/tmrev.io#29]
This is my preference, but making the background of the body darker helps with visibility and the site is less flat. I used #1d1d1d in the screenshot. I understand if you have a different vision for the project.
![DarkerBG](https://user-images.githubusercontent.com/109314127/232576535-f94f2056-9455-4c3f-a23d-f7826eb156f8.PNG)

**Comment by KegenGuyll** [comment]
@john-seredich I actually like this look alot
