### ISSUE TITLE
crash when clicking on review after making the review

### ISSUE THREAD

**Issue by Lewis-Hamilton** [tmrev/tmrev.io#86]
![image](https://github.com/tmrev/tmrev.io/assets/38916472/2d4d9b13-daa3-4a51-91e0-5e1484b2a76c)
made a review
submitted
then clicked on that review in the list of reviews for the movie

**Comment by NishantEC** [comment]
hey @KegenGuyll i'd like to work on the issue. please assign me

**Comment by KegenGuyll** [comment]
@NishantEC All yours let me know if you run into any problems!

**Comment by KegenGuyll** [comment]
This is a very easy fix, it issue is that vote is possible null

models > tmrev > review.ts > TmrevReview

on line 18 update votes to be optional. like so:

`votes?: Vote`

components > page-components > movie > reviews > reviewItem.tsx

update line `191` and `203` to

`!!review.votes?`

and that should fix the issue.

**Comment by NishantEC** [comment]
i really appreciate the help but that defeated the purpose of assigning me the task.
so, I'll  unassign myself. Thank you
